repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.1.0
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ["sqlfluff-templater-dbt", "dbt-core", "dbt-duckdb"]
      - id: sqlfluff-fix
        additional_dependencies: ["sqlfluff-templater-dbt", "dbt-core", "dbt-duckdb"]
